# =============================================================================
# Docker Compose - Python (Otimizado com Multi-stage Cache)
# =============================================================================
# Uso: docker compose up
# App: Padrão CLI/Scripts
# =============================================================================

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.python
      target: dev # Lembra dos estágios? Aqui chamamos só o ambiente de Dev!
    volumes:
      - ../:/app
    working_dir: /app
    stdin_open: true
    tty: true
    env_file:
      - ../.env.development
    environment:
      - PYTHON_ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
